[package]
name = "lambda_runtime"
version = "0.1.0"
authors = ["Stefano Buliani", "David Barsky"]
description = "Rust runtime for AWS Lambda"
keywords = ["AWS", "Lambda", "Runtime", "Rust"]
license = "Apache-2.0"
homepage = "https://github.com/awslabs/aws-lambda-rust-runtime"
repository = "https://github.com/awslabs/aws-lambda-rust-runtime"
documentation = "https://docs.rs/lambda_runtime"
edition = "2018"

[dependencies]
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
tokio = "0.1"
log = "^0.4"
lambda_runtime_core = { path = "../lambda-runtime-core", version = "^0.1" }

[dev-dependencies]
simple_logger = "^1"
simple-error = "^0.1"
failure = "^0.1"
#rusoto_core = "^0.35"
#rusoto_dynamodb = "^0.35"